### PR TITLE
container referencing name scoping support including volumes_from, af…

### PR DESCRIPTION
**Pull request by KennethNagin**
Pull request for:
Container referencing name scoping support on container create.
This includes volumes_from, affinity, and links.

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@KennethNagin Before we review the code, we should have a description of the various use case we address here (e.g., affinity, volume-from, etc..)

**Comment by doronp** [comment]
@KennethNagin I'd split it to multiple Commits each of which deals with a subject. That code which I think I once wrote part of is huge and I'd write it differently today to improve the readability.
Maybe we can do a re-Write and hence achieve both  multiple commits for multiple subjects and more readable code? WDYT?

**Comment by ezrasilvera** [comment]
@doronp @KennethNagin ok. let's re-write the CheckContainerReferences

**Comment by KennethNagin** [comment]
The containerRefeence complexity is a direct result of the fact that we do not have an efficient way to determine which containers belong to a tenant.   Thus the most basic simplification that is required is an  better more efficient way to cache a collection  of containers owned by the tenant.  Once that is created then we should be able to quickly determine whether there is a container reference in the collection.  In my opinion, only once the above is done does it make sense to break up containerReference into three distinct units, i.e. volumes_from, affinity, links.  
I suggest that two utility functions be created. 
-   func getContainers(string TenantId) (ContainerCollection).  
-   func getContainerLongId(ContainerCollection containerCollection, string containerReference) (string).  
  I am not sure which is the best structure for the ContainerCollection since the containerReference could be longId, shortId, or name.

**Pull request closed without merging**
