### PR TITLE
Swarm API tests subset for multi-tenancy.

### PR DESCRIPTION
**Pull request by andreyod**

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@andreyod I'm not sure it's reasonable to copy the actual tests because then we need to keep sync. Let's do a dynamic solution - either just put a script that will copy the needed bats, or push a special main file that will call the relevant tests.

**Comment by andreyod** [comment]
Bats files have more than 1 test case per file. Some of the files was changed and some test cases skipped. So this is not a simple copy.
This is regression testing, not sure sync is needed.

**Comment by ezrasilvera** [comment]
Oh you mean you changed some of the tests will pass on our system ?  If so you are correct but let's review which tests where changed and why ...

**Comment by andreyod** [comment]
Should pass. I just skipped some test cases.

**Pull request merged**
