### PR TITLE
Networks API naming and authorization.

### PR DESCRIPTION
**Pull request by andreyod**

### CODE REVIEW

**Comment by KennethNagin** [comment]
I think network supported should be treated as a separate plugin.  The current design merges network support nto nameScoping.go, whose focus was container name scoping.  This ireduces our flexibility and is not a very modular approach.  For instance,  it means that another approach to networking would affect the way we do container name scoping.

**Comment by KennethNagin** [comment]
Why is this network related pull request also making changes to container related commands?

**Comment by KennethNagin** [comment]
I thought we agreed that the naming convention for commands prefix with the object name followed by action,  e.g. containercreate, containerlist.  But this push is using the opposite, e.g. "deleteNetwork", "inspectNetwork".

**Comment by andreyod** [comment]
Separated network functions from nameScoping and authZ. Changed command names. Swarm integration tests are fail now as 'docker run' without --net is not supported.

**Pull request merged**
